# Generated by Django 2.2.5 on 2019-09-10 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aa', '0002_auto_20190905_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='marca_carro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name_plural': 'Marcas Carros',
                'verbose_name': 'Marca Carro',
            },
        ),
        migrations.CreateModel(
            name='modelo_carro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name_plural': 'Modelos Carros',
                'verbose_name': 'Modelo Carro',
            },
        ),
        migrations.CreateModel(
            name='veiculos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_veiculo', models.CharField(max_length=128)),
                ('cor', models.CharField(max_length=128)),
                ('combustivel', models.CharField(max_length=128)),
                ('placa', models.CharField(max_length=128)),
                ('valor', models.CharField(max_length=128)),
                ('documentacao', models.CharField(max_length=128)),
                ('ipva', models.CharField(max_length=128)),
                ('img', models.ImageField(blank=True, upload_to='static/media/')),
                ('observacao', models.CharField(max_length=1280)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aa.marca_carro')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aa.modelo_carro')),
            ],
            options={
                'verbose_name_plural': 'Veiculos',
                'verbose_name': 'Veiculo',
            },
        ),
    ]
