# Generated by Django 2.2.5 on 2019-10-21 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aa', '0003_marca_carro_modelo_carro_veiculos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veiculos',
            name='marca',
        ),
        migrations.AddField(
            model_name='modelo_carro',
            name='marca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aa.marca_carro'),
        ),
    ]
