# Generated by Django 2.2.5 on 2019-10-21 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aa', '0004_auto_20191021_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculos',
            name='usuario_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aa.usuario'),
        ),
    ]
