# Generated by Django 2.2.5 on 2019-10-22 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aa', '0005_veiculos_usuario_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='leilao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=128)),
                ('data_inicio', models.DateField(blank=True)),
                ('data_final', models.DateField(blank=True)),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aa.usuario')),
                ('veiculo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aa.veiculos')),
            ],
            options={
                'verbose_name': 'Leilao',
                'verbose_name_plural': 'Leiloes',
            },
        ),
    ]
