# Generated by Django 2.2.5 on 2019-11-05 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aa', '0007_leilao_valor_atual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leilao',
            name='usuario_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aa.usuario'),
        ),
    ]
