# Generated by Django 2.2.5 on 2019-11-05 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aa', '0008_auto_20191105_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='leilao',
            name='usuario_id_comprador',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
